<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Cabeceras exactas de la plantilla Matrixify "Orders" (Plantilla migración pedidos.xlsx).
 * El orden importa: debe coincidir 1:1 con las columnas de la plantilla.
 */
class ISE_Matrixify_Columns {

    public static function headers() {
        return array(
            'Name',
            'Command',
            'Send Receipt',
            'Inventory Behaviour',
            'Number',
            'Phone',
            'Email',
            'Note',
            'Tags',
            'Tags Command',
            'Cancelled At',
            'Cancel: Reason',
            'Cancel: Send Receipt',
            'Cancel: Refund',
            'Processed At',
            'Closed At',
            'Currency',
            'Source',
            'Source Identifier',
            'Source URL',
            'Weight Total',
            'Tax 1: Title',
            'Tax 1: Rate',
            'Tax 1: Price',
            'Tax 2: Title',
            'Tax 2: Rate',
            'Tax 2: Price',
            'Tax 3: Title',
            'Tax 3: Rate',
            'Tax 3: Price',
            'Tax: Included',
            'Tax: Total',
            'Payment: Status',
            'Additional Details',
            'Customer: ID',
            'Customer: Email',
            'Customer: Phone',
            'Customer: First Name',
            'Customer: Last Name',
            'Customer: Note',
            'Customer: State',
            'Customer: Tags',
            'Billing: First Name',
            'Billing: Last Name',
            'Billing: Name',
            'Billing: Company',
            'Billing: Phone',
            'Billing: Address 1',
            'Billing: Address 2',
            'Billing: Zip',
            'Billing: City',
            'Billing: Province',
            'Billing: Province Code',
            'Billing: Country',
            'Billing: Country Code',
            'Shipping: First Name',
            'Shipping: Last Name',
            'Shipping: Name',
            'Shipping: Company',
            'Shipping: Phone',
            'Shipping: Address 1',
            'Shipping: Address 2',
            'Shipping: Zip',
            'Shipping: City',
            'Shipping: Province',
            'Shipping: Province Code',
            'Shipping: Country',
            'Shipping: Country Code',
            'Company: ID',
            'Company: Name',
            'Company: External ID',
            'Company: Location ID',
            'Company: Location Name',
            'Company: Location External ID',
            'Line: Type',
            'Line: Command',
            'Line: Product ID',
            'Line: Product Handle',
            'Line: Title',
            'Line: Name',
            'Line: Variant ID',
            'Line: Variant Title',
            'Line: SKU',
            'Line: Quantity',
            'Line: Price',
            'Line: Discount',
            'Line: Grams',
            'Line: Requires Shipping',
            'Line: Vendor',
            'Line: Properties',
            'Line: Gift Card',
            'Line: Force Gift Card',
            'Line: Taxable',
            'Line: Tax 1 Title',
            'Line: Tax 1 Rate',
            'Line: Tax 1 Price',
            'Line: Tax 2 Title',
            'Line: Tax 2 Rate',
            'Line: Tax 2 Price',
            'Line: Tax 3 Title',
            'Line: Tax 3 Rate',
            'Line: Tax 3 Price',
            'Line: Fulfillment Service',
            'Line: Variant Barcode',
            'Refund: ID',
            'Refund: Created At',
            'Refund: Note',
            'Refund: Restock',
            'Refund: Restock Type',
            'Refund: Restock Location',
            'Refund: Send Receipt',
            'Refund: Generate Transaction',
            'Transaction: Kind',
            'Transaction: Processed At',
            'Transaction: Amount',
            'Transaction: Currency',
            'Transaction: Status',
            'Transaction: Gateway',
            'Transaction: Force Gateway',
            'Transaction: Test',
            'Transaction: Authorization',
            'Transaction: Parent ID',
            'Fulfillment: ID',
            'Fulfillment: Status',
            'Fulfillment: Processed At',
            'Fulfillment: Tracking Company',
            'Fulfillment: Location',
            'Fulfillment: Shipment Status',
            'Fulfillment: Tracking Number',
            'Fulfillment: Tracking URL',
            'Fulfillment: Send Receipt',
            // Metacampo interno de IVB: número de pedido original de WooCommerce,
            // para trazabilidad Woo <-> Shopify. Matrixify crea el metacampo de
            // pedido a partir del nombre de columna "Metafield: namespace.key [tipo]".
            'Metafield: custom.pedido_woo [single_line_text_field]',
            // Columna AUXILIAR (no es de Matrixify; la ignora al importar): el
            // nombre de usuario de WordPress del cliente. Suele ser el email
            // original con el que se registró (inmutable), que es el que a menudo
            // tiene A3 aunque el pedido lleve otro email de contacto. El resolver
            // la usa para casar pedidos con su empresa y la elimina del CSV final.
            'Woo User Login',
        );
    }
}
